# Generated by Django 5.1 on 2024-09-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_room_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="Participants",
            new_name="participants",
        ),
    ]
